/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package org.rucca.cheese.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import kotlin.collections.List
import org.rucca.cheese.model.AddMemberRequestDTO
import org.rucca.cheese.model.ChangeRoleRequestDTO
import org.rucca.cheese.model.CreateThreadRequestDTO
import org.rucca.cheese.model.ListMessagesResponseDTO
import org.rucca.cheese.model.ListThreadsResponseDTO
import org.rucca.cheese.model.MessageDTO
import org.rucca.cheese.model.PostMessageRequestDTO
import org.rucca.cheese.model.RenameThreadRequestDTO
import org.rucca.cheese.model.ThreadDTO
import org.rucca.cheese.model.ThreadDetailDTO
import org.rucca.cheese.model.ThreadMemberDTO
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface ThreadsApi {

    @Operation(
        tags = ["chat"],
        summary = "Add a member to a thread (admin+)",
        operationId = "addThreadMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Added")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/threads/{id}/members"],
        consumes = ["application/json"],
    )
    fun addThreadMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        addMemberRequestDTO: AddMemberRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Change a thread member's role (owner only)",
        operationId = "changeThreadMemberRole",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Role changed")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/threads/{id}/members/{userId}"],
        consumes = ["application/json"],
    )
    fun changeThreadMemberRole(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        changeRoleRequestDTO: ChangeRoleRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Create a thread (caller becomes owner)",
        operationId = "createThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = ThreadDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/threads"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createThread(
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        createThreadRequestDTO: CreateThreadRequestDTO?
    ): ResponseEntity<ThreadDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Dissolve a thread (owner only)",
        operationId = "dissolveThread",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Dissolved")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/threads/{id}"])
    fun dissolveThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Get thread detail plus members",
        operationId = "getThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ThreadDetailDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/threads/{id}"],
        produces = ["application/json"],
    )
    fun getThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ThreadDetailDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "List messages with cursor pagination (member+)",
        operationId = "listMessages",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListMessagesResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/threads/{id}/messages"],
        produces = ["application/json"],
    )
    fun listMessages(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "id of the first message on the page (cursor)")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListMessagesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "List a thread's members",
        operationId = "listThreadMembers",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                array =
                                    ArraySchema(
                                        schema = Schema(implementation = ThreadMemberDTO::class)
                                    )
                            )
                        ],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/threads/{id}/members"],
        produces = ["application/json"],
    )
    fun listThreadMembers(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<List<ThreadMemberDTO>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "List threads the current user is a member of",
        operationId = "listThreads",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListThreadsResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/threads"],
        produces = ["application/json"],
    )
    fun listThreads(
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListThreadsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Post a message to a thread (member+); persisted then broadcast via WebSocket",
        operationId = "postMessage",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = MessageDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/threads/{id}/messages"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun postMessage(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        postMessageRequestDTO: PostMessageRequestDTO?,
    ): ResponseEntity<MessageDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Remove a member from a thread (admin+)",
        operationId = "removeThreadMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Removed")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/threads/{id}/members/{userId}"])
    fun removeThreadMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Rename a thread (admin+)",
        operationId = "renameThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ThreadDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/threads/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun renameThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        renameThreadRequestDTO: RenameThreadRequestDTO?,
    ): ResponseEntity<ThreadDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
